name: cinque_terre_pipeline

channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - snakemake
  - mamba

  # Variant handling and genomic file utilities
  - bcftools
  - samtools
  - htslib

  # Population genomics
  - plink
  - plink2
  - king
  - eigensoft
  - shapeit5=5.1.1

  # Plotting
  - matplotlib

  # General utilities
  - coreutils
  - grep
  - sed
  - gawk
